services:
  - type: web
    name: zrevents06
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        sync: false   # à remplir manuellement avec l'URL Render
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: LOG_DASHBOARD_URL
        value: https://log-dashboard-tmye.onrender.com
      - key: LOG_DASHBOARD_KEY
        value: 977aee6f26fa58902093c9c42d449fbda38dd536ddfd19628b8ab70aa2f50244
